apiVersion: v1
kind: Service
metadata:
  name: {{ include "clean-architecture.walletApp.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "clean-architecture.walletApp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.walletApp.service.type }}
  ports:
    - port: {{ .Values.walletApp.service.port }}
      targetPort: {{ .Values.walletApp.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "clean-architecture.walletApp.selectorLabels" . | nindent 4 }}
