apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clean-architecture.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "clean-architecture.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.accountsApi.environment | quote }}
  ASPNETCORE_BASEPATH: {{ .Values.accountsApi.basePath | quote }}
  ASPNETCORE_URLS: "http://+:{{ .Values.accountsApi.containerPort }}"
  POSTGRES_HOST: {{ include "clean-architecture.postgresql.fullname" . | quote }}
  POSTGRES_PORT: {{ .Values.postgresql.port | quote }}
  POSTGRES_DB: {{ .Values.postgresql.database | quote }}
  POSTGRES_USER: {{ .Values.postgresql.username | quote }}
