blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://atypical-consulting.github.io/dotnet-clean-architecture/
    about: Check the project documentation before opening an issue.
