version: '3.4'

services:
  nginx:
    ports:
      - "8080:80"
      - "8081:443"
  accounts-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AuthenticationModule__AuthorityUrl=https://wallet.local:8081
  wallet-spa:
    build:
      args:
        ENV: docker
