version: '3.4'

services:
  accounts-api:
    image: ${DOCKER_REGISTRY-}accounts
    container_name: "accounts-api"
    build:
      context: ../accounts-api/
      dockerfile: src/WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://*:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MyCertificatePassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
      - PersistenceModule__DefaultConnection=Server=sql1;User Id=sa;Password=<YourStrong!Passw0rd>;Database=Accounts;
      - AuthenticationModule__AuthorityUrl=https://localhost:5000
    volumes:
      - ../.docker/https:/https:ro
    depends_on:
      - sql1
      - accounts-api-seed
    ports:
      - "5001:5001"
  accounts-api-seed:
    container_name: "accounts-api-seed"
    build:
      context: ../accounts-api/
      dockerfile: ../accounts-api-seed/Dockerfile
    environment:
      - PersistenceModule__DefaultConnection=Server=sql1;User Id=sa;Password=<YourStrong!Passw0rd>;Database=Accounts;
    command: bash -c "/root/.dotnet/tools/dotnet-ef database update --project src/Infrastructure --startup-project src/WebApi"
    depends_on:
      - sql1
  sql1:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "<YourStrong!Passw0rd>"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
