version: '3.4'

services:
  accounts-api:
    image: ${DOCKER_REGISTRY-}accounts
    container_name: "accounts-api"
    build:
      context: ../accounts-api/
      dockerfile: src/WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://*:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MyCertificatePassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
      - PersistenceModule__DefaultConnection=Host=postgres;Port=5432;Database=Accounts;Username=postgres;Password=YourStrong!Passw0rd
      - AuthenticationModule__AuthorityUrl=https://localhost:5000
    volumes:
      - ../.docker/https:/https:ro
    depends_on:
      - postgres
      - accounts-api-seed
    ports:
      - "5001:5001"
  accounts-api-seed:
    container_name: "accounts-api-seed"
    build:
      context: ../accounts-api/
      dockerfile: ../accounts-api-seed/Dockerfile
    environment:
      - PersistenceModule__DefaultConnection=Host=postgres;Port=5432;Database=Accounts;Username=postgres;Password=YourStrong!Passw0rd
    command: bash -c "/root/.dotnet/tools/dotnet-ef database update --project src/Infrastructure --startup-project src/WebApi"
    depends_on:
      - postgres
  postgres:
    image: "postgres:17"
    container_name: "postgres"
    environment:
      POSTGRES_PASSWORD: "YourStrong!Passw0rd"
      POSTGRES_DB: "Accounts"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
