version: '3.4'

services:
  nginx:
    build:
      context: ../nginx/
    container_name: wallet.local
    volumes:
      - ../.docker/https/localhost.crt:/etc/ssl/certs/localhost.crt:ro
      - ../.docker/https/localhost.key:/etc/ssl/private/localhost.key:ro
    links:
      - accounts-api
      - wallet-spa
  accounts-api:
    image: ${DOCKER_REGISTRY-}accounts
    container_name: "accounts-api"
    build:
      context: ../accounts-api/
      dockerfile: src/WebApi/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_BASEPATH=/accounts-api
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MyCertificatePassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
      - PersistenceModule__DefaultConnection=Host=postgres;Port=5432;Database=Accounts;Username=postgres;Password=${POSTGRES_PASSWORD:-YourStrong!Passw0rd}
    volumes:
      - ../.docker/https:/https:ro
    depends_on:
      - postgres
      - accounts-api-seed
  accounts-api-seed:
    container_name: "accounts-api-seed"
    build:
      context: ../accounts-api/
      dockerfile: ../accounts-api-seed/Dockerfile
    environment:
      - PersistenceModule__DefaultConnection=Host=postgres;Port=5432;Database=Accounts;Username=postgres;Password=${POSTGRES_PASSWORD:-YourStrong!Passw0rd}
    command: bash -c "/root/.dotnet/tools/dotnet-ef database update --project src/Infrastructure --startup-project src/WebApi"
    depends_on:
      - postgres
  wallet-spa:
    image: ${DOCKER_REGISTRY-}wallet
    container_name: "wallet-spa"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: ../wallet-spa/
  postgres:
    image: "postgres:17"
    container_name: "postgres"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-YourStrong!Passw0rd}"
      POSTGRES_DB: "Accounts"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
