apiVersion: v2
name: clean-architecture
description: A Helm chart for the Clean Architecture Manga application stack
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - dotnet
  - clean-architecture
  - accounts-api
  - wallet-app
  - postgresql
maintainers:
  - name: Atypical Consulting
    url: https://github.com/Atypical-Consulting
